export const UserActionTypes = {
    SET_AUTHENTICATED: 'SET_AUTHENTICATED',
    SET_UNAUTHENTICATED: 'SET_UNAUTHENTICATED',
    SET_USER: 'SET_USER',
    LOADING_USER: 'LOADING_USER',
    MARK_NOTIFICATIONS_READ: 'MARK_NOTIFICATIONS_READ'
};

export const UiActionTypes = {
    SET_ERRORS: 'SET_ERRORS',
    LOADING_UI: 'LOADING_UI',
    LOADING_DATA: 'LOADING_DATA',
    CLEAR_ERRORS: 'CLEAR_ERRORS',
    STOP_LOADING_UI: 'STOP_LOADING_UI'
};
export const DataActionTypes = {
    SET_SCREAMS: 'SET_SCREAMS',
    SET_SCREAM: 'SET_SCREAM',
    LIKE_SCREAM: 'LIKE_SCREAM',
    UNLIKE_SCREAM: 'UNLIKE_SCREAM',
    DELETE_SCREAM: 'DELETE_SCREAM',
    POST_SCREAM: 'POST_SCREAM',
    SUBMIT_COMMENT: 'SUBMIT_COMMENT'
};